### ISSUE TITLE
[AI] Infra: Other: Triton Compiler Crash (1 job)

### ISSUE THREAD

**Issue by dhonnappa-amd** [dhonnappa-amd/build-dashboards-testing#3235]
## AI Analysis — Infrastructure Issue: Other: Triton Compiler Crash

**1 affected job**

| Pipeline/Build | Queue | Job Link |
|---------------|-------|----------|
| amd-ci/7177 | `amd_mi325_4` | [View job](https://buildkite.com/vllm/amd-ci/builds/7177#019d47a0-fd12-4877-9a92-fd48bd595c38) |

---

### Summary

This build job was testing a Nemotron-H model (Mamba-based architecture) on AMD MI325X GPUs using vLLM's v1 executor with tensor parallelism (TP=4). The job successfully completed infrastructure setup, including git checkout, Docker daemon initialization, and ROCm environment verification. The model began executing inference workloads, and during the forward pass through the Mamba mixer layer, vLLM attempted to compile a Triton kernel for the chunk scan operation. The Triton compiler's autotuner tried to benchmark different kernel configurations for the AMD gfx942 architecture (MI325X), but the PassManager failed during the 'make_ttgir' compilation stage with a RuntimeError. This is a compiler crash in the Triton AMD backend, not a GPU hang, test failure, or infrastructure issue. The failure is deterministic for this specific model/kernel combination and represents a real regression or incompatibility between the Triton compiler version, the Mamba kernel implementation, and the AMD ROCm backend. The subsequent Docker container cleanup error is merely a symptom of the worker process terminating unexpectedly.

---

### Root Cause Analysis

Walking through the log chronologically: (1) Infrastructure setup completed successfully - git clone, Docker daemon started after 30s wait, ROCm 6.12.12 detected, MI325X GPUs enumerated. (2) The test script launched a vLLM worker with TP=4 for a Nemotron-H model. (3) During model execution at 08:44:28, Worker_TP3 (pid=6007) entered the forward pass and reached the mamba_mixer2 layer. (4) The Mamba chunk scan kernel triggered Triton's autotuner to compile optimized kernels for AMD gfx942. (5) During compilation, the Triton AMD backend's PassManager crashed with 'RuntimeError: PassManager::run failed' in the make_ttgir stage. This is the FIRST UNRECOVERABLE error - there were no retries, no fallback compilation paths. The worker process immediately shut down, and the job failed. The Docker cleanup error that followed is a consequence, not a cause.

---

### Detected Events (all affected jobs)

**amd-ci/7177** (queue: `amd_mi325_4`):
- `other:triton compiler crash`: (Worker_TP3 pid=6007) ERROR 04-01 08:44:28 [multiproc_executor.py:949]   File "/usr/local/lib/python3.12/dist-packages/triton/backends/amd/compiler.py", line 264, in make_ttgir
(Worker_TP3 pid=6007) ERROR 04-01 08:44:28 [multiproc_executor.py:949]     pm.run(mod, 'make_ttgir')
(Worker_TP3 pid=6007) ERROR 04-01 08:44:28 [multiproc_executor.py:949] RuntimeError: PassManager::run failed
  - _The Triton compiler's PassManager failed during the make_ttgir stage while compiling a Mamba chunk scan kernel for AMD ROCm. This is a compiler-level failure, not a runtime GPU hang or test failure._
- `other:triton compiler crash`: (Worker_TP3 pid=6007) ERROR 04-01 08:44:28 [multiproc_executor.py:949]   File "/usr/local/lib/python3.12/dist-packages/vllm/model_executor/layers/mamba/ops/ssd_chunk_scan.py", line 469, in _chunk_scan_fwd
(Worker_TP3 pid=6007) ERROR 04-01 08:44:28 [multiproc_executor.py:949]     _chunk_scan_fwd_kernel[grid](
(Worker_TP3 pid=6007) ERROR 04-01 08:44:28 [multiproc_executor.py:949]   File "/usr/local/lib/python3.12/dist-packages/triton/runtime/jit.py", line 370, in <lambda>
  - _The failure occurred during Triton kernel autotuning for the Mamba chunk scan forward pass. The autotuner was attempting to compile different kernel configurations when the compiler crashed._
- `other:triton compiler crash`: (Worker_TP3 pid=6007) ERROR 04-01 08:44:28 [multiproc_executor.py:949]   File "/usr/local/lib/python3.12/dist-packages/vllm/model_executor/models/nemotron_h.py", line 942, in forward
(Worker_TP3 pid=6007) ERROR 04-01 08:44:28 [multiproc_executor.py:949]     hidden_states = self.model(
(Worker_TP3 pid=6007) ERROR 04-01 08:44:28 [multiproc_executor.py:949]   File "/usr/local/lib/python3.12/dist-packages/vllm/model_executor/layers/mamba/mamba_mixer2.py", line 928, in mamba_mixer2
  - _The job was running a Nemotron-H model (a Mamba-based architecture) when it attempted to execute the mamba_mixer2 operation, which triggered Triton kernel compilation that subsequently failed._
- `docker_daemon`: FAILEDError response from daemon: No such container: rocm_36d7f19897843c9cbdb701ba88d0f2c29954fe44_KwTTmtIhwl
^^^ +++
🚨 Error: The command exited with status 1
  - _After the worker process crashed due to the Triton compiler failure, the cleanup script attempted to remove a Docker container that no longer existed. This is a consequence of the earlier failure, not the root cause._

---

#### Immediate Fix

Pin to a known-good Triton version that successfully compiles Mamba kernels for AMD gfx942, or disable Triton compilation for this specific kernel by setting VLLM_USE_TRITON=0 and falling back to native ROCm kernels. Check if there's a Triton AMD backend patch available for gfx942 PassManager issues.

#### Suggested Code Change

```
In .buildkite/scripts/hardware_ci/run-amd-test.sh or the test environment setup, add: export VLLM_USE_TRITON=0 before launching vLLM. Alternatively, in vllm/model_executor/layers/mamba/ops/ssd_chunk_scan.py, add a try-except around the Triton kernel compilation with fallback to a non-Triton implementation: try: _chunk_scan_fwd_kernel[grid](...) except RuntimeError as e: if 'PassManager::run failed' in str(e): logger.warning('Triton compilation failed, falling back to native kernel'); return _chunk_scan_fwd_native(...)
```

#### Prevention

Add a pre-merge CI test that specifically validates Triton kernel compilation for all Mamba operations on AMD gfx942 without actually running inference. Pin Triton version in requirements-rocm.txt to a tested version. Add monitoring to detect PassManager failures and automatically file issues with Triton upstream. Consider maintaining a compatibility matrix of Triton versions vs ROCm versions vs GPU architectures.

#### Workaround

Temporarily skip Nemotron-H/Mamba model tests on AMD MI325X until Triton compiler is fixed. Use VLLM_USE_TRITON=0 environment variable to disable Triton compilation globally. Alternatively, test with a different Triton commit known to work with ROCm 6.12.12 and gfx942, or downgrade ROCm to 6.11.x if that version has better Triton compatibility.

---

_This issue was automatically created by the AI log analysis pipeline._
